### ISSUE TITLE
How can I map the exit mode function to Ctrl + [ ?

### ISSUE THREAD

**Issue by Atomadeus** [bernardo-bruning/godot-vim#13]
The ESC key is not convenient to use, and I want to map the exit mode function to Ctrl+[ key. How can I do that?

Looking forward to your response.

**Comment by WhoStoleMyCoffee** [comment]
Hi, Atomadeus!
Normally, you'd configure your key mappings in `key_map: Array[Dictionary] in key_map.gd`.
Sadly, custom keybindings in Insert mode isn't a feature yet, although you *can* implement it yourself by digging into the code (see `func back_to_normal_mode() in cursor.gd`), but that's just inconvenient.

I'll make a pull request implementing this feature.
Cheers!

**Comment by Atomadeus** [comment]
Alright, I got it, thanks for your reply.
