### ISSUE TITLE
Does it work with Godot 4.2?

### ISSUE THREAD

**Issue by berarma** [bernardo-bruning/godot-vim#15]
I've installed it but it does nothing. Do I have to activate it somehow? I'm new to this plugin.

Thanks.

**Comment by WhoStoleMyCoffee** [comment]
Hi :)
Have you enabled the plugin?
Go under `Project` -> `Project Settings` in the `Plugins` tab.  You should see a list of plugins detected by Godot (scanned from inside `res://addons/`).
Make sure "enabled" is checked for `GodotVim`

**Comment by berarma** [comment]
Ah, sorry, it's been some time since last time I installed a plugin. Yes, it works. Thanks!
