### ISSUE TITLE
plugin conflicts with simple project files.

### ISSUE THREAD

**Issue by froismo** [bernardo-bruning/godot-vim#4]
I tried to install the plugin, and conflicts with common project files made me backtrack.

![image](https://github.com/bernardo-bruning/godot-vim/assets/1802249/b1935ea5-0355-40e9-a93a-d774a99aaeaa)

**Comment by froismo** [comment]
v4.1.1.stable.official [bd6af8e0e] on windows

**Comment by bernardo-bruning** [comment]
Hello @froismo, I fixed it and submitted a new version to Godot Assets. Thanks for registering this issue. :smile: 
After updating your version from 0.2 to 0.3 close the issue if not get a problem.
